spring:
  profiles:
    active: prod

  # MongoDB Configuration
  data:
    mongodb:
      host: ${MONGODB_HOST:mongodb-cluster}
      port: ${MONGODB_HOST:27017}
      username: ${MONGODB_USERNAME:admin}
      password: ${MONGODB_PASSWORD:MgPr0dp@ssAdmin++}
      database: ${MONGODB_DATABASE:ticketing_prod}
      authentication-database: ${MONGODB_AUTHENTICATION_DATABASE:admin}
      pool:
        max-size: 100
        min-size: 5
        max-idle-time-ms: 30000
        max-life-time-ms: 60000

    # Redis Configuration
    redis:
      host: ${REDIS_HOST:redis-cluster}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      timeout: 5000
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2
          max-wait: 2000ms

# Server Configuration for Development
server:
  port: ${SERVER_PORT:8081}
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

# Management Configuration for Development
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never
  prometheus:
    metrics:
      export:
        enabled: true

# Logging Configuration for Development
logging:
  level:
    root: WARN
    com.ticketing: INFO
    org.springframework: WARN
    org.mongodb: WARN
  file:
    name: ${LOG_FILE_PATH:/var/log/ticketing/ticketing-core.log}
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 90
      total-size-cap: 10GB

# Development specific properties
app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:86400000}
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:https://ticketing.company.com}
      allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE}
      allowed-headers: ${CORS_ALLOWED_HEADERS:*}
      max-age: ${CORS_MAX_AGE:3600}

  cache:
    redis:
      ttl: 300 # 5 minutes for faster development

  business:
    max-tickets-per-user: 100 # Higher limit for development
    ticket-expiry-hours: 1 # Shorter expiry for testing

# Development tools
debug: true
trace: false
